train:
  num_epochs: 10
  batch_size: 64
  learning_rate: 0.001
  optimizer: adam
  early_stopping: True
  patience: 5

model:
  dropout_rate: 0.1
  n_temporal_aware_block: 3 
  n_filter: 64
  output_len: 50 
  cont: False
  use_kan: False
  kernel_size: 2
