train:
  num_epochs: 500
  batch_size: 64
  learning_rate: 0.001 #0.000001
  optimizer: adam
  early_stopping: True
  patience: 5
  lr_scheduler: 0.25
  label_smoothing: 0.1

model:
  dropout_rate: 0.1 # 0.2
  n_temporal_aware_block: 8 # 10
  n_filter: 39
  num_features: 39
  ck: False
  use_kan: False
  kernel_size: 2
  omega_0: 25
  is_siren: True 
