train:
  num_epochs: 100
  batch_size: 16
  learning_rate: 0.001
  optimizer: adam
  early_stopping: True
  patience: 5
  weight_decay: 1e-5


model:
  dropout_rate: 0.1
  n_temporal_aware_block: 3 
  n_filter: 64
  num_features: 182 
  tab_cont: False
  cont: False
  use_kan: False
  kernel_size: 2
